"""integration secrets

Revision ID: d2fd7cf589ba
Revises: 38e7f6194fec
Create Date: 2026-09-26 11:04:26.914196
"""
from alembic import op
import sqlalchemy as sa


revision = 'd2fd7cf589ba'
down_revision = '38e7f6194fec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('masked', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_secrets_name'), 'integration_secrets', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_secrets_name'), table_name='integration_secrets')
    op.drop_table('integration_secrets')
    # ### end Alembic commands ###
